oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix: /platform


#routes CoreBundle, sans préfixe
oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
